version: "3"
services:
  test:
    build:
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./results:/app/results
      - ./processdata:/app/processdata
      - ./src:/app/src
    command: python /app/src/main.py
