version: "3"
services:
  test:
    build:
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./:/app
    command: python /app/main.py
